{{- range $clientSecret := .Values.acme.clientSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $clientSecret.name }}
type: Opaque
data:
  CLIENT_SECRET: {{ $clientSecret.value | b64enc | quote }}
{{- end }}
