repositories:
  - name: jenkins
    url: https://charts.jenkins.io

releases:
  - name: jenkins
    namespace: jenkins
    chart: jenkins/jenkins
    values:
      - jenkins.yaml
    secrets:
      - jenkins-secrets.yaml
