creation_rules:
  - path_regex: .*
    key_groups:
      - age:
        # thor
        - age1vqm5gwkmf38jsmt3j4lm3fdslausskaadtz360ewn0g7z2fchahqyr694v
        # ghactions
        - age1kfafc2k5remh9j7k0gz884p3xhvegv8mzyek2nf75fwhrfa86vhsrseepw
        # blackpanther
        - age1y562y0u4k8y0eyq56s4g00ssd2cduamddcgfpu8fs7t00pfjss2s9nymt8
        # antman
        - age1lv53trxftjem0a4hewf9h9dmp65cql6ycaj5q8kvfnfspccg747s6lxpxg
