creation_rules:
  - path_regex: .*
    key_groups:
      - age:
        # thor
        - age1vqm5gwkmf38jsmt3j4lm3fdslausskaadtz360ewn0g7z2fchahqyr694v
        # ghactions
        - age1kg5j06vpay75xpetn4h35ezu8qchknyjt2g7wzx8cm3d06vs0yxq503880
        # blackpanther
        - age1y562y0u4k8y0eyq56s4g00ssd2cduamddcgfpu8fs7t00pfjss2s9nymt8
