---
metrics:
  enabled: true

#controller:
#  # Configures the ports the nginx-controller listens on
#  containerPort:
#    http: 80
#    https: 443
#  service:
#    ports:
#      http: 80
#      https: 443

#    targetPorts:
#      http: http
#      https: https

## TCP service key:value pairs
## Ref: https://github.com/kubernetes/contrib/tree/master/ingress/controllers/nginx/examples/tcp
###
#tcp: {}
##  8080: "default/example-tcp-svc:9000"

## UDP service key:value pairs
## Ref: https://github.com/kubernetes/contrib/tree/master/ingress/controllers/nginx/examples/udp
###
#udp: {}
##  53: "kube-system/kube-dns:53"
