repositories:
  - name: halkeye
    url: https://halkeye.github.io/helm-charts

releases:
  - name: foundry-vtt
    chart: halkeye/foundry-vtt
    version: 1.3.0
    namespace: foundry-vtt
    values:
      - foundry-vtt.yaml
    secrets:
      - foundry-vtt-secrets.yaml
