{{/* Make sure all variables are set properly */}}
{{- include "bjw-s.common.loader.init" . }}

{{/* Append the hardcoded volumes */}}
{{- define "authentik.generate_secrets" -}}
{{- include "authentik.secret" (dict "root" . "values" .Values.authentik) }}
{{- if $.Values.geoip.enabled }}
GEOIPUPDATE_ACCOUNT_ID: {{ required "geoip account id required" .Values.geoip.accountId | toString | b64enc | quote }}
GEOIPUPDATE_LICENSE_KEY: {{ required "geoip license key required" .Values.geoip.licenseKey | toString | b64enc | quote }}
{{- end }}
{{- end -}}
{{- $_ := mergeOverwrite .Values (include "authentik.generate_secrets" . | fromYaml) -}}

{{/* Render the templates */}}
{{ include "bjw-s.common.loader.generate" . }}
