apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-secrets" (include "bjw-s.common.lib.chart.names.fullname" .) }}
  {{- with (include "bjw-s.common.lib.metadata.allLabels" $ | fromYaml) }}
  labels: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with (include "bjw-s.common.lib.metadata.globalAnnotations" $ | fromYaml) }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- include "authentik.secret" (dict "root" . "values" .Values.authentik) | indent 2 }}
  {{- if $.Values.geoip.enabled }}
  GEOIPUPDATE_ACCOUNT_ID: {{ required "geoip account id required" .Values.geoip.accountId | toString | b64enc | quote }}
  GEOIPUPDATE_LICENSE_KEY: {{ required "geoip license key required" .Values.geoip.licenseKey | toString | b64enc | quote }}
  {{- end }}
