controllers:
  main:
    replicas: 1
    strategy: RollingUpdate
    containers:
      main:
        image:
          repository:  ghcr.io/nginxinc/nginx-s3-gateway/nginx-oss-s3-gateway
          tag: unprivileged-oss-20230518
        env:
          S3_BUCKET_NAME: not-the-plants
          S3_REGION: sfo3
          S3_SERVER_PORT: "443"
          S3_SERVER_PROTO: https
          S3_SERVER: sfo3.digitaloceanspaces.com
          S3_STYLE: virtual
          AWS_REGION: "sfo3"
          AWS_SIGS_VERSION: "4"
          ALLOW_DIRECTORY_LIST: "false"
          PROVIDE_INDEX_PAGE: "true"
        envFrom:
          - secretRef:
              name: not-the-plants-secret
        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /health
                port: 8080
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readiness: *probes
          startup:
            enabled: false
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop: ["ALL"]
        #    add: ["NET_BIND_SERVICE"]
        #  sysctls:
        #    - name: "net.ipv4.ip_unprivileged_port_start"
        #      value: "1"
        resources:
          limits: &resources
            memory: 256Mi
          requests:
            <<: *resources
            cpu: 10m
    pod:
      securityContext:
        runAsUser: 101
        runAsGroup: 101
        runAsNonRoot: true
        capabilities:
          drop: ["ALL"]
          #add: ["NET_BIND_SERVICE"]
      #  sysctls:
      #    - name: "net.ipv4.ip_unprivileged_port_start"
      #      value: "1"
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: not-the-plants

service:
  main:
    ports:
      http:
        port: 8080

ingress:
  main:
    enabled: true
    hosts:
      - host: &host "not-the-plants.g4v.dev"
        paths:
          - path: /
            service:
              name: main
              port: http

persistence:
  tmp:
    enabled: true
    type: emptyDir
