helmDefaults:
  kubeContext: do-k8s

repositories:
  - name: halkeye
    url: https://halkeye.github.io/helm-charts
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: redis
    chart: bitnami/redis
    namespace: databases
    values:
      - redis.yaml
    secrets:
      - redis-secrets.yaml
  - name: postgresql
    chart: bitnami/postgresql
    version: 11.1.8
    namespace: databases
    values:
      - postgresql.yaml
    secrets:
      - postgresql-secrets.yaml
  - name: pgadmin
    chart: halkeye/pgadmin
    namespace: databases
    values:
      - pgadmin.yaml
    secrets:
      - pgadmin-secrets.yaml
  - name: mariadb
    chart: bitnami/mariadb
    namespace: databases
    values:
      - mariadb.yaml
    secrets:
      - mariadb-secrets.yaml
  - name: phpmyadmin
    chart: bitnami/phpmyadmin
    namespace: databases
    values:
      - phpmyadmin.yaml
