#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: stevenolen/mailgun-smtp-server
  # -- image tag
  # @default -- chart.appVersion
  tag: latest
  # -- image pull policy
  pullPolicy: IfNotPresent

# -- secret variables. See more environment variables in the [mailgun-smtp-server documentation](https://github.com/stevenolen/mailgun-smtp-server).
# @default -- See below
secret:
  # -- mailgun api key
  MG_KEY: ""
  # -- mailgun domain
  MG_DOMAIN: ""

env: {}
  # -- can be passed to allow more than 4 simulatenous connections
  # MG_SMTPD_SIMULATENOUS_CONNECTIONS: 4
  # -- maps to opts parameter in midi-smtp-server's Smtpd class.
  # MG_SMTPD_OPTIONS: ""

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 25

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence: {}
  # data:
  #   enabled: false
  #   mountPath: /data

