helmDefaults:
  kubeContext: do-k8s
  cleanupOnFail: true

repositories:
  - name: halkeye
    url: https://halkeye.github.io/helm-charts

releases:
  - name: synapse
    chart: halkeye/synapse
    version: 0.36.0
    namespace: matrix
    values:
      - ./synapse.yaml
    secrets:
      - ./synapse-secrets.yaml

  - name: element-web
    chart: halkeye/element-web
    namespace: matrix
    version: 1.28.0
    values:
      - ./element-web.yaml

  - name: schildichat-web
    chart: halkeye/schildichat-web
    version: 1.2.0
    namespace: matrix
    values:
      - ./schildichat-web.yaml

  - name: mautrix-signal
    chart: halkeye/mautrix-signal
    namespace: matrix
    version: 0.3.0
    values:
      - ./mautrix-signal.yaml
    secrets:
      - ./mautrix-signal-secrets.yaml
