repositories:
  - name: k8s-at-home
    url: https://k8s-at-home.com/charts/
releases:
  - name: wikijs
    namespace: wikijs
    chart: k8s-at-home/wikijs
    values:
      - wikijs.yaml
    secrets:
      - wikijs-secrets.yaml
