repositories:
  - name: k8s-at-home
    url: https://k8s-at-home.com/charts/

releases:
  - name: unifi
    chart: k8s-at-home/unifi
    namespace: unifi
    values:
      - unifi.yaml
    secrets:
      - unifi-secrets.yaml
