---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "app.fullname" . }}-config
  annotations:
    {{- include "app.annotations" . | indent 4 }}
  labels:
    {{- include "app.labels" . | indent 4 }}
data: {{ toYaml .Values.config.variables | nindent 2 }}
