---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "app.fullname" . }}
  labels:
    {{- include "app.labels" . | indent 4 }}
  annotations:
    {{- include "app.annotations" . | indent 4 }}
spec:
  replicas: {{ .Values.replicas }}
{{- if .Values.strategy }}
  strategy:
{{ toYaml .Values.strategy | indent 4 }}
{{ if eq .Values.strategy.type "Recreate" }}
    rollingUpdate: null
{{- end }}
{{- end }}
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | indent 6 }}
  template:
    metadata:
      labels:
        {{- include "app.labels" . | indent 8 }}
{{ with .Values.podLabels }}{{ toYaml . | indent 8 }}{{ end }}
      annotations:
        checksum/configMap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- include "app.annotations" . | indent 8 }}
{{ with .Values.podAnnotations }}{{ toYaml . | indent 8 }}{{ end }}
    spec:
      hostNetwork: {{ .Values.hostNetwork }}
      serviceAccountName: {{ template "app.serviceAccountName" . }}
      containers:
        - name: caddy
          image: caddy:2.4.6-alpine
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
          command:
            - sh
            - -c
            - |-
                cat << EOF > /etc/caddy/Caddyfile
                localhost {
                        respond "localhost"
                }

                {{- range $.Values.relays }}
                http://{{ .hostname }}, https://{{ .hostname }} {
                        reverse_proxy {{.backend.scheme | default "https"}}://{{ .backend.ip }}:{{ .backend.port }} {
                                header_up Host {{ .backend.hostname }}
                                header_up X-Forwarded-Host {host}
                                transport http {
                                        {{- if eq (.backend.scheme | default "https") "https" }}
                                        tls_server_name {{ .backend.hostname }}
                                        tls_insecure_skip_verify
                                        {{- end }}
                                }
                        }
                }

                {{- end }}
                EOF
                caddy run -config /etc/caddy/Caddyfile
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.command }}
          command: {{ toYaml . | nindent 16 }}
          {{- end }}
          {{- with .Values.args }}
          args: {{ toYaml . | nindent 16 }}
          {{- end }}
          env:
            - name: TAILSCALED_STATE
              value: kube:{{ .Values.rbac.stateSecretName }}
          envFrom:
            - configMapRef:
                name: {{ template "app.fullname" . }}-config
            - secretRef:
                name: {{ template "app.fullname" . }}-config
          ports:
            - name: exporter
              containerPort: 8080
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe: {{ toYaml . | nindent 16 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe: {{ toYaml . | nindent 16 }}
          {{- end }}
          {{- with .Values.resources }}
          resources: {{ toYaml . | nindent 16 }}
          {{- end }}
          {{- with .Values.securityContext }}
          securityContext: {{ toYaml . | nindent 16 }}
          {{- end }}
      {{- with .Values.hostAliases }}
      hostAliases: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
