{{- $releaseName := .Release.Name -}}
{{- range $.Values.relays }}
{{- if not .skipIngress }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ $releaseName }}-{{ .hostname | replace ".g4v.dev" ".g4v" | replace "." "-" }}"
  labels:
{{ include "app.labels" $ | indent 4 }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .ingressClassName }}
  ingressClassName: .
  {{- end }}
  tls:
  - hosts:
    - {{ .hostname }}
    secretName: {{ $releaseName }}-{{.hostname | replace ".g4v.dev" ".g4v" | replace "." "-" }}-tls
  rules:
    - host: {{ .hostname }}
      http:
        paths: {{ concat (list (dict "path" "/" "backend" (dict "service" (dict "name" $releaseName "port" (dict "name" "http"))) "pathType" "Prefix")) (.additionalPaths | default (list)) | toYaml | nindent 10 }}

{{- end }}
{{- end }}
