{{- range $.Values.relays }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "dev-home-relay-{{ .hostname | replace ".g4v.dev" ".g4v" | replace "." "-" }}"
  labels:
{{ include "app.labels" $ | indent 4 }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - {{ .hostname }}
    secretName: home-relay-{{.hostname | replace ".g4v.dev" ".g4v" | replace "." "-" }}-tls
  rules:
    - host: {{ .hostname }}
      http:
        paths: {{ concat (list (dict "path" "/" "backend" (dict "service" (dict "name" "home-relay" "port" (dict "name" "http"))) "pathType" "Prefix")) (.additionalPaths | default (list)) | toYaml | nindent 10 }}

{{- end }}
