{{- if .Values.rbac.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "app.serviceAccountName" . }}
  annotations:
    {{- include "app.annotations" . | indent 4 }}
  labels:
    {{- include "app.labels" . | indent 4 }}
{{ end }}
