repositories:
  - name: sstarcher
    url: https://shanestarcher.com/helm-charts/
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
releases:
  - name: prometheus
    chart: prometheus-community/prometheus
    version: 15.12.0
    namespace: monitoring
    values:
      - prometheus.yaml
    secrets:
      - prometheus-secrets.yaml
  - name: helm-exporter
    chart: sstarcher/helm-exporter
    version: 1.2.2+6766a95
    namespace: monitoring
  - name: kube-state-metrics
    chart: bitnami/kube-state-metrics
    namespace: monitoring
    version: 3.2.2
