helmDefaults:
  kubeContext: do-k8s
  cleanupOnFail: true

repositories:
  - name: sstarcher
    url: https://shanestarcher.com/helm-charts/
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: wiremind
    url: https://wiremind.github.io/wiremind-helm-charts

releases:
  - name: prometheus
    chart: prometheus-community/prometheus
    version: 25.24.0
    namespace: monitoring
    values:
      - prometheus.yaml
    secrets:
      - prometheus-secrets.yaml
  - name: helm-exporter
    chart: sstarcher/helm-exporter
    version: 1.2.16+77ad21d
    namespace: monitoring
  - name: grafana
    chart: grafana/grafana
    namespace: monitoring
    version: 8.3.3
    values:
      - grafana.yaml
    secrets:
      - grafana-secrets.yaml
  - name: karma
    chart: wiremind/karma
    namespace: monitoring
    version: 2.6.1
    values:
      - karma.yaml
