discord_api_url: ENC[AES256_GCM,data:kQrE6zr/pqtS76jBC3NMXtkFFV8ZMfaPn5bwbPtEMxuNjjvzp0DqU4tqUD5amibDi3+zmrBgvaE2hgF/K5IjAjjfQ/ESfi/1XhIP8r4vZPQlqz4Xf5GYbRwHOOvJDN80TTF4nF6LRlQDUvmBqkVsXRjsWoa6yhRV,iv:qEeQyD4PvhiDXSyqUFwctXFujqQAvNVRx7tWtP/KJyw=,tag:jZ1PXB4jp8rkK4Km8/bi9Q==,type:str]
alertmanager:
    config:
        global:
            #ENC[AES256_GCM,data:KlFYqwQOkFtNUVKyLyQNR8dfOVEyOfPtwaNxTGkat+6wklt07F9+0yN9En3EbQj7084f0URjgXNKdkQ=,iv:5Rs/PLec3xZRBUNyX6XjZb2VWjS7hRsSLpdOlBnZDP0=,tag:sVqLtkRU0go6hKAbhuNVbQ==,type:comment]
            smtp_smarthost: ENC[AES256_GCM,data:Yx639vGQfvwKiuuP3HdlFGUdkBeL+IrSOVkoOKr8302/,iv:YEV2cHQGjuha6Pmf2g9YKWySOHonKk2Uqx8jKsKqaB8=,tag:Xs+gDy48E5Sm/axn/DfkuQ==,type:str]
            smtp_from: ENC[AES256_GCM,data:sM7W+CF2kQnCjSBdeGTf4TIn21c=,iv:2XFSUSNtLhneG7+U461Ncd2592aiJRjq0ZDeiSeKzz0=,tag:5gpGyCxkZ95NHH2Syahb4A==,type:str]
        route:
            receiver: ENC[AES256_GCM,data:Tzh6L1hJpQ==,iv:0aYcR0Bpio8/4NDH9EPhAP8c35/5q6lhXkSIfISdmC4=,tag:T1q4r/0s+SqtlK8pq3zoCQ==,type:str]
            routes:
                - receiver: ENC[AES256_GCM,data:pPaEUQ==,iv:AQ2rGz/g/Th4aJ957KmkuIGcFXn05yMEmfkFJljzTBk=,tag:gVz/TR292sgMesSYkgqddA==,type:str]
                  matchers:
                    - ENC[AES256_GCM,data:m5wlmlHef5TY514SAx3ZgBR46Q4=,iv:jzkwL6DDGtqMLE0SGvHfS1UZUoQH/3gyQzhliDD/DdI=,tag:vZ+SA+XRlQdMmhL4XtZnbg==,type:str]
                  continue: ENC[AES256_GCM,data:IEwAyVw=,iv:0xtpI72MWsRLZFUarkxPzqfbmONV9t4DOjdeqUZs84o=,tag:dmqlWMndJ0bRSEBITWfpnA==,type:bool]
                - receiver: ENC[AES256_GCM,data:pPaEUQ==,iv:AQ2rGz/g/Th4aJ957KmkuIGcFXn05yMEmfkFJljzTBk=,tag:gVz/TR292sgMesSYkgqddA==,type:str]
                  matchers:
                    - ENC[AES256_GCM,data:E/2OKTo+ZFj6s/uFTakx8Djg,iv:jTwSh9hCTfq6dZE+IYY3jUvZxwnPqt9YdClcs7U4D6o=,tag:Y0fnWPDUe9eTsm7yn6XH0g==,type:str]
                - receiver: ENC[AES256_GCM,data:jYZDSkWh4Q==,iv:NZbd+GykaP5U9KIb8cmJ0nXFVwAnhOmAFcWqd8zO3hM=,tag:330EiTlpTZfnJ7FeRfL2dw==,type:str]
        receivers:
            - name: ENC[AES256_GCM,data:Ztq93Q==,iv:6m1tzJVd7Kx8UKJ44VTWGPH9xqqTsDghdr0ZGGOqnTY=,tag:5FkOL9y2mZBBbZxbRDZarw==,type:str]
            - name: ENC[AES256_GCM,data:s2X78jO/HA==,iv:k3Nq5Pjb3m8ugLO2MpltKbaIkuUc4y+AWbG/DbNWnPU=,tag:b+hfqpcMIUIrJ3WPBSCAfg==,type:str]
              discord_configs:
                - webhook_url: ENC[AES256_GCM,data:V8Jt8XTMNttc0QmHdd49Vq2vnDwi3GMVR1JcHE2HZfDVl1wkJTxJogE0dLZz/jyacTJYUJkQ1P5XiHFswMdpKdymCJrQ6lNCL5kPkWTI7L9dx3J/1ep5UETF7mH371KeXb+PhTCI1r0h16SnH1dN9PNWOdN1F74T,iv:Xdyqj34D3Fhe96+D6Y/TeavfL2oQ0hY4aFU+2TZgacU=,tag:4rUwx27kMtXS+2zBPY2nfQ==,type:str]
                  send_resolved: ENC[AES256_GCM,data:Fj/IWA==,iv:lBopjczr92gnGRGWKWPm8ZTs016obSPDH3OUoyJENqY=,tag:DQRNtj+q10nmo4R96ZY7tg==,type:bool]
                  title: ENC[AES256_GCM,data:9ZgTDiI1f7rHOwhTKmLmhNFW4co/LLugM18J/SNFlDiRUb5QYmANzJgohlmeOM42UbRhN6CusdO36CObGxgT3afsHMi1stl3fDE7pD1fny/XVIgKeVVZKEkOIhs07UibvxSqKn0uHAr3/SDngSbKCgvCKdPFFATxvdNOaE6b/RGWxpQi8CXbCTfU6QTZwbhh7dTl9KkoEaJ2KAPImfTPRQ6i1GNKlNTXB4jG5hbJZah/6xWLCAXqqEusiQcKh6wX83vbZwnaiYRYBwdhCDqaC2gPyBsp6DyEOoGmDlfca+4b7P5m3+bcaBoXVyUjdOy2urqpdunUcD6XvuCDxcfc/oCPvc6TUTZx5ipymVFkm7jg5r7VUkPiNtzrO1fbpkmJ286D+fmbqZ6D8hB+Q74VDzlDZS9ScrVBJY67aOFDZzhKxrCDV2+0g7eKTYpw+1N7FcDfRV0AGGXrUn1iHhggzwwdkqnKcP/HYtxO+5NepuZ9bcDi3UOU,iv:X9H3YFu7kZssnpxxMpBTNGKBebEr+yr7eq71djIYcrE=,tag:6/y4qOgGJ6N66IF8/5Zaaw==,type:str]
                  message: ENC[AES256_GCM,data:/Jd8hNttdzgLIFHj/TvboBEfG13mSbrLC7M7/ZaxxTGTGPt13JrE2N3Rcp59Zq4dKMH7424gTyMz3wYAVJDIXJjRth0qbG9QA6l56chn3+OgciA1KS1jjfoA4Nv6466cr9hhH7OBKgMKmEAUyNJ973m4uIEiXkpK1mdKBZZNDSAKzWx7vG9oZFC4TipnFuyMoW2uVAtUWP6+1vaSvrpS9/5YiXSR+GS9109mv/6Am1ET6HCsS2eQUu8WUlCUIOcXw5j+AGsD/Shs+Z6TwFA8XhN/Luti+ebRUaRqLBBSbGq2cpdvxALw6HpWxI1fJwB+ARcLR1y5gAKE0GjrS5mF1RMD8/uvfEqxdnTZX50vMZuR4pHlsnFMVaqdEaCVNtExp40VvkCWpMyPAlTzHp+K2Gs4RB868+XC3viATyLaOTi7l2mvxZhXsj+IewHwlbQFY4tCuF9XK/22pTugMqCE3Hr3+k4l2RLR2WQlG4lFqqWjCcEQcP8h0Fo6J6h2hkayrlKhxQ5dReCv47XzWrLgHu4RgprxnLPRouvlxM+LW1Gw86vkuLr8UIzOkmIY3K8MJQHq/8sDRkFtEuaK88Q+1m6joRDzX1pq8EK8Wv7Iq2vc+G0znNu7mt8=,iv:O3Tl4Uthd9Tcp7LlUiG2W0tePgx8Hyss1FMwWtmRnNg=,tag:RKpNttA0J5RVnckqNEzZ0w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vqm5gwkmf38jsmt3j4lm3fdslausskaadtz360ewn0g7z2fchahqyr694v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRU3lVanFvMTBsSXBRN0M4
            d3gvZmJ5Zk1JaTdzSUdaTmVQWmg5WHFaQmw4CnZjcmNBdG1PVVRiNzFMMndyQkI3
            RVJKcjJnbGpFaDJieWp5dUZrMWhKQkEKLS0tIElrcmNJbERybXdaRHcrQ3B4THJr
            Tk9rdjVQTFFuT3dPQWpTNENYcmlHbHcKh1EfMHuxWGvg4ikGOaPiyeqv8PO6bEwv
            nXJdF4PLvaG1QnMulRplDczs3wEbwZUDUuKQjIGGvw47kSb/n4LTDA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1kfafc2k5remh9j7k0gz884p3xhvegv8mzyek2nf75fwhrfa86vhsrseepw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3Q0R4cjVNVThhS0VhOEpV
            UG1FSzU5dll1N1k0NjJOY2dVWnIrTzQyYjN3Ckprd001alE3bFB1eTFRZnJONm5v
            a25wOERuUzlCNm9TWGxsRkl5SmxLNTgKLS0tIDhXZ1Z0WDFDUC8yVXVySzhpK1Rw
            Y3kyYTNESjNMdnlFUmNsaU1IcmxWRU0KQKLz9yl3DS3N7NLv8kY+KqA3Rk13zEqh
            wstV+OGSh56Mh//SH1j521hVdAWLkrJjpbLhAuvR3eKFshKBBcz4iA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y562y0u4k8y0eyq56s4g00ssd2cduamddcgfpu8fs7t00pfjss2s9nymt8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAydWZxZFV3QkFXZjdEUjEx
            c1ZtRGp4UWxkNXRhZUkzc09MamRVRWY4L25RCkhWZDFWT2hOa0JWajNvdmc1eUFD
            bElFaHdWcXZwa3MxZ2NYSHhrbGw3N0EKLS0tIHVTVE11REJyYmlpREd0K2hjNmtv
            c1R2cXdCVktmKzZhd2VIRnc5NkY5S2sKXjUlCWrfVhMhpXv6FRDe3A3R/B6U7FfU
            TFIn4UKTvA/7n/B3uAm5QcdN1rPYjLtMlZTXa6qCeoKqGRc7PDFKTw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lv53trxftjem0a4hewf9h9dmp65cql6ycaj5q8kvfnfspccg747s6lxpxg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Q0VqWXBkSE1oUXZoaUVo
            QkljcnFkL24zY0Y3RzRWTTZkYnNjS1J2NHk0CmZacmo4NVBFcmpoNEZzS2pYR0wz
            UVFlU3A1L1hxNHlQTE5kWE8yYXFVVzAKLS0tIFBnNEhnRzgvcW9UWXhKekVUVm9O
            M0g5YWlRaWN5UmF2S1F4L0xZSC9NZFEKcqxJ71gF6Cdf91epT1TJREImKB+9n2tA
            nVcNzAihKGqjhLu96VOHfraxFALCnn/wf4TvOoCXyHPTUSF1H8vnEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-13T04:27:50Z"
    mac: ENC[AES256_GCM,data:wA4N3srN4vF/Gpp++/QXgG1LIh7yjIksQuqoXkB6lQ3ECmLVPP6kNUinfIbiMRapLW3wl1vYISMsLkFLb1SZ9iuU+3OjG4+OQPEXXMBeKCRoU+n8rmfyEOgsSg0JORGnD60sgM3Ld1DUgxwfJI01WYBjQkl7BpkGSVchEQ769ME=,iv:HJPGa+VcOTbaFv+pZQ7k/pwaODWD8rtTjUoJ56aKW2I=,tag:N4huBhO8oNhHb3oX+zdRUQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
