---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name:  {{ template "openldap.fullname" . }}-tls
spec:
  secretName:  {{ template "openldap.fullname" . }}-tls
  dnsNames:
  {{- range .Values.dnsNames }}
  - {{ . }}
  {{- end }}
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
