---
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: halkeye
    url: https://halkeye.github.io/helm-charts

releases:
  - name: g4v-do-wildcard-certificate
    chart: halkeye/certificate
    version: 0.0.4
    namespace: kube-system
    values:
      - issuerRef:
          kind: ClusterIssuer
          name: letsencrypt
        dnsNames:
          - '*.g4v.dev'
        commonName: '*.g4v.dev'
        secretName: wildcard-do-g4v-tls
  - name: ingress-nginx
    namespace: kube-system
    chart: ingress-nginx/ingress-nginx
    version: 4.5.0
    values:
      - ingress-nginx.yaml
  - name: external-dns
    namespace: kube-system
    chart: bitnami/external-dns
    version: 6.13.2
    values:
      - external-dns.yaml
    secrets:
      - external-dns-secrets.yaml
