metrics:
  enabled: true
rbac:
  create: true
controller:
  ingressClassResource:
    default: true

  extraArgs:
    default-ssl-certificate: "kube-system/wildcard-do-g4v-tls"

  stats:
    enabled: true

  metrics:
    enabled: true
    port: 10254

#  kind: "DaemonSet"

  config:
    use-forwarded-headers: "true"
    use-proxy-protocol: "true"
    custom-http-errors: >-
      401,403,404,500,501,502,503

  service:
    type: LoadBalancer
    externalTrafficPolicy: Local
    publishService:
      enabled: "true"
    annotations:
      external-dns.alpha.kubernetes.io/hostname: "*.g4v.dev."
      "service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol": "true"
      "service.beta.kubernetes.io/do-loadbalancer-hostname": "do.g4v.dev"
      prometheus.io/scrape: "true"
      prometheus.io/port: "10254"


#defaultBackend:
#  enabled: true
#  image:
#    repository: ghcr.io/tarampampam/error-pages
#    tag: 2.17.0
#  extraEnvs:
#  - name: TEMPLATE_NAME # Optional: change the default theme
#    value: l7-dark
#  - name: SHOW_DETAILS # Optional: enables the output of additional information on error pages
#    value: 'false'
