metrics:
  enabled: true
rbac:
  create: true
controller:
  ingressClassResource:
    default: true

  extraArgs:
    default-ssl-certificate: "kube-system/wildcard-do-g4v-tls"

  stats:
    enabled: true

  metrics:
    enabled: true
    port: 10254

  kind: "DaemonSet"

  config:
    use-forwarded-headers: "true"
    use-proxy-protocol: "true"

  service:
    type: LoadBalancer
    externalTrafficPolicy: Local
    publishService:
      enabled: "true"
    annotations:
      external-dns.alpha.kubernetes.io/hostname: "*.g4v.dev."
      "service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol": "true"
      "service.beta.kubernetes.io/do-loadbalancer-hostname": "do.g4v.dev"
      prometheus.io/scrape: "true"
      prometheus.io/port: "10254"
