# Default values for acme.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
#
acme:
  id: "letsencrypt-prod"
  email: ""
  server: "https://acme-v02.api.letsencrypt.org/directory"

  # Secrets used for dns01 settings
  clientSecrets:
    - name: 'acme_test_secret'
      value: 'password'

  # Accepts any values as defined here https://cert-manager.io/docs/configuration/acme/dns01/
  dns01: {}
