helmDefaults:
  kubeContext: do-k8s

repositories:
  - name: halkeye
    url: https://halkeye.github.io/helm-charts

releases:
  - name: postfix
    chart: halkeye/postfix
    namespace: smtp
    values:
      - postfix.yaml
    secrets:
      - postfix-secrets.yaml

  - name: smtp
    chart: ../../charts/mailgun-smtp-server
    namespace: smtp
    secrets:
      - mailgun-smtp-server-secrets.yaml

