helmDefaults:
  kubeContext: do-k8s

repositories:
  - name: halkeye
    url: https://halkeye.github.io/helm-charts
  - name: bokysan-postfix
    url: https://bokysan.github.io/docker-postfix

releases:
  - name: postfix
    chart: bokysan-postfix/mail
    version: v4.0.2
    namespace: smtp
    secrets:
      - postfix-secrets.yaml
