helmDefaults:
  kubeContext: do-k8s

repositories:
  - name: authelia
    url: https://charts.authelia.com

releases:
  - name: authelia
    namespace: authelia
    chart: authelia/authelia
    version: 0.8.2
    values:
      - authelia.yaml
    secrets:
      - authelia-secrets.yaml
