name: CI

on:
  push:
    branches:
      - main
      - github-actions
env:
  SOPS_AGE_KEY_FILE: ${{ github.workspace }}/.sops.age.keyfile.txt
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: quay.io/roboll/helmfile:v0.143.0
      options: -u 0:0

    steps:
      - uses: actions/checkout@v3

      #- name: Setup helmfile
      #  uses: mamezou-tech/setup-helmfile@v1.2.0

      - name: write sops age file
        env:
          SOPS_AGE_CONTENTS: ${{ secrets.SOPS_AGE_KEY_FILE }}
        run: |
          echo "$SOPS_AGE_CONTENTS" > $SOPS_AGE_KEY_FILE

      - name: Write ~/.kube/config
        env:
          DIGITAL_OCEAN_KUBECONFIG: ${{ secrets.DIGITAL_OCEAN_KUBECONFIG }}
        run: |
          mkdir -p $HOME/.kube
          echo "$DIGITAL_OCEAN_KUBECONFIG" > $HOME/.kube/config

      #- name: Setup helmfile
      #  uses: mamezou-tech/setup-helmfile@v1.2.0

      - name: Sops Binary Installer
        uses: mdgreenwald/mozilla-sops-action@v1.4.1

      - name: Show Configuration
        run: |
          helmfile --version
          helm version
          kubectl version --client

      - name: Helmfile Repos update
        run: |
          helmfile repos

      - name: Lint
        run: |
          helmfile lint

      - name: Make sure cert-manager is installed
        if: "github.event_name != 'pull_request'"
        env:
          TAILSCALE_CLIENT_ID: "${{ secrets.TAILSCALE_CLIENT_ID }}"
          TAILSCALE_CLIENT_SECRET: "${{ secrets.TAILSCALE_CLIENT_SECRET }}"
        run: |
          kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.7.1/cert-manager.yaml
          curl -qs https://raw.githubusercontent.com/tailscale/tailscale/d38abe90be0738f097ba79abed0a50af226b16f7/cmd/k8s-operator/manifests/operator.yaml | sed "s/# SET CLIENT ID HERE/$TAILSCALE_CLIENT_ID/; s/# SET CLIENT SECRET HERE/$TAILSCALE_CLIENT_SECRET/" | kubectl apply -f -
          sops -d cert-manager-cluster-issuer-secrets.yml | kubectl apply -f -

      - name: Diff on Pull Request
        if: "github.event_name == 'pull_request'"
        run: |
          helmfile --no-color diff --suppress-secrets --skip-deps --context=2 --concurrency=8

      - name: Diff on Pull Request
        if: "github.event_name != 'pull_request'"
        run: |
          helmfile apply --suppress-secrets --concurrency=8

