name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  SOPS_AGE_KEY_FILE: ${{ github.workspace }}/.sops.age.keyfile.txt
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: write sops age file
        env:
          SOPS_AGE_CONTENTS: "${{ secrets.SOPS_AGE_KEY_FILE }}"
        run: |
          echo "${SOPS_AGE_CONTENTS}" > "${SOPS_AGE_KEY_FILE}"

      - name: Write ~/.kube/config
        env:
          DIGITAL_OCEAN_KUBECONFIG: ${{ secrets.DIGITAL_OCEAN_KUBECONFIG }}
        run: |
          mkdir -p "${HOME}/.kube"
          echo "$DIGITAL_OCEAN_KUBECONFIG" > "${HOME}/.kube/config"
          chmod 700 -R "${HOME}/.kube"

      - name: Sops Binary Installer
        uses: mdgreenwald/mozilla-sops-action@v1.5.0

      - name: Helmfile Repos update
        uses: helmfile/helmfile-action@v1.6.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          helmfile-args: repos
          helm-plugins: >
            https://github.com/databus23/helm-diff --version 3.1.3,
            https://github.com/hypnoglow/helm-s3 --version 0.9.2,
            https://github.com/aslafy-z/helm-git --version 0.11.1,
            https://github.com/jkroepke/helm-secrets --version 4.5.0

      - name: Helmfile lint
        uses: helmfile/helmfile-action@v1.6.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          helmfile-args: lint

      - name: Make sure cert-manager is installed
        if: "github.event_name != 'pull_request'"
        env:
          TAILSCALE_CLIENT_ID: "${{ secrets.TAILSCALE_CLIENT_ID }}"
          TAILSCALE_CLIENT_SECRET: "${{ secrets.TAILSCALE_CLIENT_SECRET }}"
        run: |
          kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.7.1/cert-manager.yaml
          curl -qs https://raw.githubusercontent.com/tailscale/tailscale/d38abe90be0738f097ba79abed0a50af226b16f7/cmd/k8s-operator/manifests/operator.yaml | sed "s/# SET CLIENT ID HERE/$TAILSCALE_CLIENT_ID/; s/# SET CLIENT SECRET HERE/$TAILSCALE_CLIENT_SECRET/" | kubectl apply -f -
          sops -d cert-manager-cluster-issuer-secrets.yaml | kubectl apply -f -

      - name: Diff on Pull Request
        if: "github.event_name == 'pull_request'"
        uses: helmfile/helmfile-action@v1.6.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          helmfile-args: --no-color diff --suppress-secrets --skip-deps --context=2 --concurrency=8

      - name: Apply
        if: "github.event_name != 'pull_request'"
        uses: helmfile/helmfile-action@v1.6.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          helmfile-args: apply --suppress-secrets --concurrency=8
